### ISSUE TITLE
steps

### ISSUE THREAD

**Issue by wn13083405221** [JamesLuoau/Self-Driving-Car-Vehicle-Detection#1]
@JamesLuoau please tell me the steps to run this code,thanks

**Comment by jluo-bgl** [comment]
Hi, I have added below doc into readme.md

Run This Project

Install Miniconda

Documentation: https://conda.io/docs/install/quick.html

wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh

bash Miniconda3-latest-Linux-x86_64.sh
Install all dependencies

https://conda.io/docs/using/envs.html#share-an-environment

conda env create -f environment.yml
python --version to check python version, you should have python 3.5

Main EntryPoint

./main.py
