### ISSUE TITLE
Sincelery request for the steps to run the code

### ISSUE THREAD

**Issue by wn13083405221** [JamesLuoau/Self-Driving-Car-Vehicle-Detection#2]
I am sincelery request for the steps to run the code,please tell me ,thanks you very much, my email : 2425176429@qq.com  @JamesLuoau @ryan-keenan

**Comment by JamesLuoau** [comment]
Hi, Which part of this project?

**Comment by jluo-bgl** [comment]
Hi, I have added how to run part into Readme.md

Run This Project

Install Miniconda

Documentation: https://conda.io/docs/install/quick.html

wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh

bash Miniconda3-latest-Linux-x86_64.sh
Install all dependencies

https://conda.io/docs/using/envs.html#share-an-environment

conda env create -f environment.yml
python --version to check python version, you should have python 3.5

Main EntryPoint

./main.py
