### ISSUE TITLE
 python环境

### ISSUE THREAD

**Issue by vehery** [JamesLuoau/Self-Driving-Car-Vehicle-Detection#4]
正在学习你的代码，请问需要python的版本是多少呢？没找到requirements.txt文件，能告知一下吗？谢谢

**Comment by JamesLuoau** [comment]
我是用的conda,刚刚有commit environment.yml文件，希望能有所帮助，主要是tensorflow

**Comment by vehery** [comment]
谢谢你的更新，我再试一下
